#Each new term in the Fibonacci sequence is generated by adding the
#previous two terms. By starting with 1 and 2, the first 10 terms
#will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do
#not exceed four million, find the sum of the even-valued terms.

total = 2
numA = 1
numB = 2
num = 0
while num <4000000:
    num = numA + numB
    if num%2 == 0: total = total + num
    numA = numB
    numB = num  
print total
